### ISSUE TITLE
[Transaction/history enpoint] Wrong time on mobile client 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#656] opened 2023-08-24 10:03 UTC
request : https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0xfcFab1Eb61d3b1E8ff8F1eF1CD8e46F8be30b77f/transactions/history?timezone_offset=7200000
"If the time_zone_offset-parameter is  0, then the backend  sends a wrong timestamp of 1686573612000 which is Mon Jun 12 2023 12:40:12 GMT+0000 and Mon Jun 12 2023 14:40:12 GMT+0200 (Central European Summer Time)  When it should be 8:40 UTC to be 10:40CEST.

**Comment by iamacook** [comment] 2023-08-29 16:40
I've looked into this and we are returning timestamps in UTC according to the specified `timezone_offset` correctly.

I've [summarised my findings](https://5afe.slack.com/archives/C03CT23SU1Z/p1693326951011139?thread_ts=1692867490.034979&cid=C03CT23SU1Z) and am waiting to see what the mobile team says.

**Comment by iamacook** [comment] 2023-08-29 17:07
Mobile have confirmed that the issue is on their end so I will close this.

**Closed by iamacook** 2023-08-29 17:07 UTC
Labels: bug
